## Documentation: http://docs.travis-ci.com/user/languages/julia/
#
language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

branches: master

script:
  # Need to install the NREL registry
  - julia -e 'import Pkg;
              Pkg.Registry.add("General");
              Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/NREL/JuliaRegistry.git"));
              Pkg.build();
              Pkg.test(coverage=true)'

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
