FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Install NREL root certs.
# Uncomment the following lines (5-7) if you're using devcontainers on a NREL machine
# RUN curl -fsSLk -o /usr/local/share/ca-certificates/nrel_root.crt https://raw.github.nrel.gov/TADA/nrel-certs/v20180329/certs/nrel_root.pem && \
#   curl -fsSLk -o /usr/local/share/ca-certificates/nrel_xca1.crt https://raw.github.nrel.gov/TADA/nrel-certs/v20180329/certs/nrel_xca1.pem && \
#   update-ca-certificates