name = "PRASFiles"
uuid = "a2806276-6d43-4ef5-91c0-491704cd7cf1"
authors = [
    "Gord Stephen <Gord.Stephen@nrel.gov>",
    "Surya Chandan Dhulipala <SuryaChandan.Dhulipala@nrel.gov>"
]
version = "0.7.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
PRASCore = "c5c32b99-e7c3-4530-a685-6f76e19f7fe2"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"

[compat]
Dates = "1"
HDF5 = "0.16,0.17"
PRASCore = "0.7"
TimeZones = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
