name = "PRASCapacityCredits"
uuid = "2e1a2ed5-e89d-4cd3-bc86-c0e88a73d3a3"
authors = ["Gord Stephen <gord.stephen@nrel.gov>"]
version = "0.7.0"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
PRASCore = "c5c32b99-e7c3-4530-a685-6f76e19f7fe2"

[compat]
Distributions = "0.25"
PRASCore = "0.7 - 0.8"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
