name = "PRAS"
uuid = "05348d26-1c52-11e9-35e3-9d51842d34b9"
authors = [
    "Gord Stephen <Gord.Stephen@nrel.gov>",
    "Surya Chandan Dhulipala <SuryaChandan.Dhulipala@nrel.gov>",
    "Hari Sundar <Hari.Sundar@nrel.gov>"
]
version = "0.8.0"

[deps]
PRASCapacityCredits = "2e1a2ed5-e89d-4cd3-bc86-c0e88a73d3a3"
PRASCore = "c5c32b99-e7c3-4530-a685-6f76e19f7fe2"
PRASFiles = "a2806276-6d43-4ef5-91c0-491704cd7cf1"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
PRASCapacityCredits = "0.7"
PRASCore = "0.8.0"
PRASFiles = "0.8.0"
Reexport = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
